print("updating...")
print("reading update...")
fh1 = open("Clock.py","rb")
update = fh1.read()
fh1.close()
print("writing update")
fh2 = open("Clock.pystartup","wb")
fh2.write(update)
fh2.close()
print("updating finished.")
